# Exported from Render on 2024-05-11T11:19:29Z
services:
- type: web
  name: laravel_auth_repo
  runtime: docker
  repo: https://github.com/denishrana23/laravel_auth_repo
  branch: master
  plan: free
  envVars:
  - key: APP_KEY
    sync: false
  - key: DB_CONNECTION
    sync: false
  - key: DATABASE_URL
    sync: false
  region: singapore
  dockerContext: .
  dockerfilePath: ./Dockerfile
version: "1"
